# Generated by Django 3.2.9 on 2021-11-26 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='timestamp',
            new_name='notification_sent_time',
        ),
        migrations.RenameField(
            model_name='subscriptions',
            old_name='timestamp',
            new_name='subscribe_time',
        ),
    ]
