# Generated by Django 3.2.9 on 2021-12-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Failed', 'Failed'), ('Completed', 'Completed')], default='In Progress', max_length=120),
        ),
    ]
