# Generated by Django 3.2.9 on 2021-11-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0002_auto_20211126_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='endpoint',
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
