# Generated by Django 3.2.9 on 2021-12-06 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0003_alter_subscriptions_endpoint'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notifications',
            new_name='Notification',
        ),
        migrations.RenameModel(
            old_name='Subscriptions',
            new_name='Subscription',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='notification_sent_time',
            new_name='sent_time',
        ),
    ]
